### ISSUE TITLE
Wrong merge method used in `Minion_Migration_Manager::sync_migration_files()`

### ISSUE THREAD

**Issue by zeelot** [kohana/minion#15]
Line 222 of `Minion_Migration_Manager` is using `array_keys($installed) + array_keys($available)` which overwrites keys and causes some migration files to 'vanish'. It should be written with `Arr::merge()` or `array_merge()`.

`$all_migrations = array_merge(array_keys($installed), array_keys($available));`

**Comment by bobeagan** [comment]
closed by f7a15027d9da198eaf6f677ee75b4f4d386cf703 - uses array_merge instead of + to prevent overwriting of migrations
