### ISSUE TITLE
Error during unit test

### ISSUE THREAD

**Issue by bobeagan** [kohana/minion#19]
Fatal error: Uncaught exception 'RuntimeException' with message 'Trying to @cover not existing method "Minion_Migration_Util::extract_migration_info_from_filename".' in /usr/local/lib/php/PHP/CodeCoverage/Util.php:589

**Comment by BRMatt** [comment]
Fixing @covers notation in util tests, closed by e52563165c52490dff540bee73a2b46ce52d417d
