### ISSUE TITLE
All of the minion migration tests fail if no unittest connection exists

### ISSUE THREAD

**Issue by bobeagan** [kohana/minion#20]
Minion_Migration_ModelTest::test_fetch_all
Undefined index:  unittest

[..]/modules/unittest/classes/kohana/unittest/database/testcase.php:85
[..]/modules/unittest/classes/kohana/unittest/database/testcase.php:60

_Note: this is on a Kohana 3.0.x project_

Excluding inclusion of all the others as they say the same thing; undefined index: unittest

**Comment by BRMatt** [comment]
Well you need to specify a database connection else the tests can't run...

**Comment by bobeagan** [comment]
Right, and I do that in my cascading configs that load specific to the environment.  I don't think I should have to create a separate database group just for unit tests.  It should be handled by the developer based on Kohana::$environment instead.

**Comment by BRMatt** [comment]
This is more of an issue with kohana's unittest module as it provides the database test case that minion uses

**Comment by bobeagan** [comment]
Right, I will move my issue over there.

http://dev.kohanaframework.org/issues/3677
