### ISSUE TITLE
ORM model generation

### ISSUE THREAD

**Issue by alexeyco** [kohana/minion#22]
Hi!

In my fork of your wonderful framework I have implemented the possibility of generating ORM models. I think it's fairly common features that will be useful to you.

**Comment by BRMatt** [comment]
We're trying to refactor tasks out from the minion core into separate repositories (you might have noticed the kohana-minion/tasks-migrate repo) so I'm afraid this won't be getting merged in.

**Comment by alexeyco** [comment]
Guys, I just gave you the idea, you do with it what you want.

**Comment by BRMatt** [comment]
Ok, well thanks for the suggestion :)
