### ISSUE TITLE
Location aliases and preventing autoload errors

### ISSUE THREAD

**Issue by alexeyco** [kohana/minion#23]
Hi!

In order to avoid any mistakes, at which the structure breaks down the names of classes, I decided to use something called aliases. I can not for a long time to explain what I mean and I can just invite you to download my fork of your framework and insight into:

  php --uri=minion --locations

Accordingly, this functional is used in the generation of ORM models. For example:

  php --uri=minion/model:generate --name=test --location=application

**Comment by BRMatt** [comment]
Ported over to new project for migrations https://github.com/kohana-minion/tasks-migrations/issues#issue/3
