### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by bobeagan** [kohana/minion#25]
The compatibility section from the readme is outdated now that the separate 3.0 and 3.1 branches have been created.

**Comment by BRMatt** [comment]
Fixed in https://github.com/kohana-minion/core/commit/f216e0df599a3a2f6803b5a5cc16af3f5a935dbe and https://github.com/kohana-minion/core/commit/f41141c9e0db9072691213f9d40c8b1f1621fd4a
