### ISSUE TITLE
Incorrect migration class name generated by db:generate

### ISSUE THREAD

**Issue by ahutchings** [kohana/minion#3]
If I run the following command
    php public/index.php --uri=minion/db:generate --location=application/migrations/ --description="Add one-to-many relationship"

the migration class name that results is
    Migration__20110107011624

It seems that this is happening because Minion_Task_Db_Generate->_generate_classname() expects migrations to be in a subfolder of the migrations folder, but I'm not sure if that is desired for application migrations.

**Comment by BRMatt** [comment]
Fix classname bug in db:generate when an empty location is used. closed by 64fec1190bb2973746cc62c3ab5f0f9ad1bc2cf2
