### ISSUE TITLE
Deprecated binary notice

### ISSUE THREAD

**Issue by ThePixelDeveloper** [kohana/minion#35]
Have the binary pass in a minion version number. If that doesn't match with the source code then issue a notice telling the user to copy over the new binary.

Useful feature for future upgrades imho.

**Comment by BRMatt** [comment]
Personally I think it's easier to just use a symlink to the bash script shipped with the module. Thoughts?

**Comment by ThePixelDeveloper** [comment]
Yep, that is good too. This ticket is more about informing the user of a newer binary if one exists.

**Comment by zeelot** [comment]
the symlink isn't really an option for developers because they can't commit that to the repo. Everyone that works on the project would need to make the symlink, no?

**Comment by BRMatt** [comment]
Symlinks can be committed just fine

**Comment by zeelot** [comment]
I guess I don't know what happens when a windows user pulls that change in.
