### ISSUE TITLE
Rename $_config to $_parameters

### ISSUE THREAD

**Issue by zeelot** [kohana/minion#47]
It's quite a bit confusing to call it config when we have Kohana configs. I also often load a config file and want to call it $config but can't.

What do you guys think? Should I rename it?

```
class Minion_Task_Foo {

    protected $_parameters = array(
        'some_param' => 'value',
    );

    public function execute(array $parameters)
    {
        ...
        $config = Kohana::$config->load('something');
    }

}
```

**Comment by zeelot** [comment]
<Kiall> Agreed .. But flags/options/arguments are more common names for them than parameters
<Kiall> arguments =  "./minion bla"
<Kiall> flags/options = "./minion --verbose"
<Kiall> (thats the usual naming i've seen around anyway ..)

I like `$_options` as it seems the simplest to understand

**Comment by BRMatt** [comment]
Agreed, options is better

**Comment by zeelot** [comment]
This has been done
