### ISSUE TITLE
Automatically migrations schema on first db:migrate call

### ISSUE THREAD

**Issue by ThePixelDeveloper** [kohana/minion#9]
Instead of having to import the schema into the database, it'd be nice to have minion automatically create the database schema when you first run `db:migrate`

**Comment by BRMatt** [comment]
I can't remember off the top of my head, but doesn't kohana's db library require a database to exist in order to connect to it?

**Comment by ThePixelDeveloper** [comment]
I missed a word in my title "Automatically execute migrations schema on first db:migrate call".

Yeah it does, you're executing migrations against a database so you will know it's going to exist. I'm saying it'd be nice to check if the migrations table was already there and if it wasn't, then run schema.sql against it.

**Comment by BRMatt** [comment]
Ah I see, sorry I misread this and thought you wanted the database creating.

**Comment by BRMatt** [comment]
Ensure the migrations table exists before running migrations, closed by 5648f47110efb42c1ce1e2c009a8c486453ff3c7
